### ISSUE TITLE
dflate error

### ISSUE THREAD

**Issue by aharalambopoulos** [bramfeld/wanproxy#1]
I have setup a simple tcp client-server setup trying to send a simple packet from the client to server.
I get an error on the client

1593091078.437157 [/zlib/inflate] ERR: virtual bool InflateFilter::consume(Buffer&, int): inflate(): data error

**Comment by bramfeld** [comment]
Please launch the program in verbose mode (-v) and report the whole diagnostic messages you get. Also, it would be helpful to have the configuration you are using and a description of how you are calling your client.

**Comment by haralambop** [comment]
Server 
-------

create codec codec0
set codec0.codec XCodec
set codec0.cache COSS
set codec0.cache_path "/var/lib/wanproxy"
set codec0.local_size 2048
set codec0.compressor zlib
set codec0.compressor_level 6
set codec0.byte_counts 1
activate codec0

create interface if0
set if0.family IPv4
set if0.host "172.17.0.5"
set if0.port "3300"
set if0.proto TCP
activate if0

create peer peer0
set peer0.family IPv4
set peer0.host "10.50.50.7"
set peer0.port "16509"
set peer0.proto TCP
activate peer0

create proxy proxy0
set proxy0.interface if0
set proxy0.interface_codec codec0
set proxy0.peer peer0
set proxy0.peer_codec None
set proxy0.role Server
activate proxy0


1594640759.275205 [/wanproxy] INFO: WANProxy MT 3.0.5
1594640759.275236 [/wanproxy] INFO: Copyright (c) 2008-2013 WANProxy.org
1594640759.275246 [/wanproxy] INFO: Copyright (c) 2013-2018 Bramfeld-Software
1594640759.275252 [/wanproxy] INFO: All rights reserved.
1594640759.275279 [/wanproxy/config] INFO: Configuring WANProxy.
1594640759.276701 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Cache file: /var/lib/wanproxy/81877f83-8c01-4e8e-973e-eddce88f5ac8.wpc
1594640759.276732 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Max size: 2148409344
1594640759.276737 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe size: 1056768
1594640759.276742 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe header size: 8192
1594640759.276753 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Serial: 1
1594640759.276760 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe number: 0
1594640759.276772 [/wanproxy/config/cache/type] INFO: 1
1594640759.276783 [/wanproxy/config/cache/path] INFO: /var/lib/wanproxy
1594640759.276791 [/wanproxy/config/cache/size] INFO: 2048
1594640759.276803 [/wanproxy/config/cache/uuid] INFO: 81877f83-8c01-4e8e-973e-eddce88f5ac8
1594640759.277095 [/wanproxy/proxy0/listener] INFO: Listening on: [172.17.0.5]:3300
1594640759.277120 [/event/system] INFO: Starting event system.
1594640759.277190 [/io/thread] INFO: Starting IO thread.
1594640762.072489 [/wanproxy/proxy0/listener] DEBUG: void ProxyListener::accept_complete(Event, Socket*): Accepted client: [10.50.50.10]:57580
1594640762.072744 [/wanproxy/proxy0/connector] DEBUG: void ProxyConnector::on_request_data(Event): Flushing request
1594640762.072964 [/wanproxy/proxy0/connector] DEBUG: void ProxyConnector::on_response_data(Event): Flushing response


Client
------

create codec codec0
set codec0.codec XCodec
set codec0.cache COSS
set codec0.cache_path "/var/lib/wanproxy"
set codec0.local_size 2048
set codec0.compressor zlib
set codec0.compressor_level 6
set codec0.byte_counts 1
activate codec0

create interface if0
set if0.family IPv4
set if0.host "172.17.0.2"
set if0.port "3300"
set if0.proto TCP
activate if0

create peer peer0
set peer0.family IPv4
set peer0.host "10.50.50.7"
set peer0.port "3300"
set peer0.proto TCP
activate peer0

create proxy proxy0
set proxy0.interface if0
set proxy0.interface_codec codec0
set proxy0.peer peer0
set proxy0.peer_codec None
set proxy0.role Client
activate proxy0


1594640757.212075 [/wanproxy] INFO: WANProxy MT 3.0.5
1594640757.212108 [/wanproxy] INFO: Copyright (c) 2008-2013 WANProxy.org
1594640757.212119 [/wanproxy] INFO: Copyright (c) 2013-2018 Bramfeld-Software
1594640757.212129 [/wanproxy] INFO: All rights reserved.
1594640757.212155 [/wanproxy/config] INFO: Configuring WANProxy.
1594640757.213511 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Cache file: /var/lib/wanproxy/e2582903-602d-4066-a70f-89181ad6d16c.wpc
1594640757.213541 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Max size: 2148409344
1594640757.213550 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe size: 1056768
1594640757.213559 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe header size: 8192
1594640757.213569 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Serial: 1
1594640757.213579 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe number: 0
1594640757.213593 [/wanproxy/config/cache/type] INFO: 1
1594640757.213604 [/wanproxy/config/cache/path] INFO: /var/lib/wanproxy
1594640757.213614 [/wanproxy/config/cache/size] INFO: 2048
1594640757.213623 [/wanproxy/config/cache/uuid] INFO: e2582903-602d-4066-a70f-89181ad6d16c
1594640757.213897 [/wanproxy/proxy0/listener] INFO: Listening on: [172.17.0.2]:3300
1594640757.213926 [/event/system] INFO: Starting event system.
1594640757.214019 [/io/thread] INFO: Starting IO thread.
1594640762.072737 [/wanproxy/proxy0/listener] DEBUG: void ProxyListener::accept_complete(Event, Socket*): Accepted client: [172.17.0.1]:53946
1594640762.073236 [/zlib/inflate] ERR: virtual bool InflateFilter::consume(Buffer&, int): inflate(): data error
1594640762.073252 [/wanproxy/proxy0/connector] DEBUG: void ProxyConnector::on_request_data(Event): Flushing request
1594640762.074017 [/wanproxy/proxy0/connector] DEBUG: void ProxyConnector::on_response_data(Event): Flushing response

**Comment by aharalambopoulos** [comment]
Server 
-------

create codec codec0
set codec0.codec XCodec
set codec0.cache COSS
set codec0.cache_path "/var/lib/wanproxy"
set codec0.local_size 2048
set codec0.compressor zlib
set codec0.compressor_level 6
set codec0.byte_counts 1
activate codec0

create interface if0
set if0.family IPv4
set if0.host "172.17.0.5"
set if0.port "3300"
set if0.proto TCP
activate if0

create peer peer0
set peer0.family IPv4
set peer0.host "10.50.50.7"
set peer0.port "16509"
set peer0.proto TCP
activate peer0

create proxy proxy0
set proxy0.interface if0
set proxy0.interface_codec codec0
set proxy0.peer peer0
set proxy0.peer_codec None
set proxy0.role Server
activate proxy0


1594640759.275205 [/wanproxy] INFO: WANProxy MT 3.0.5
1594640759.275236 [/wanproxy] INFO: Copyright (c) 2008-2013 WANProxy.org
1594640759.275246 [/wanproxy] INFO: Copyright (c) 2013-2018 Bramfeld-Software
1594640759.275252 [/wanproxy] INFO: All rights reserved.
1594640759.275279 [/wanproxy/config] INFO: Configuring WANProxy.
1594640759.276701 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Cache file: /var/lib/wanproxy/81877f83-8c01-4e8e-973e-eddce88f5ac8.wpc
1594640759.276732 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Max size: 2148409344
1594640759.276737 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe size: 1056768
1594640759.276742 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe header size: 8192
1594640759.276753 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Serial: 1
1594640759.276760 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe number: 0
1594640759.276772 [/wanproxy/config/cache/type] INFO: 1
1594640759.276783 [/wanproxy/config/cache/path] INFO: /var/lib/wanproxy
1594640759.276791 [/wanproxy/config/cache/size] INFO: 2048
1594640759.276803 [/wanproxy/config/cache/uuid] INFO: 81877f83-8c01-4e8e-973e-eddce88f5ac8
1594640759.277095 [/wanproxy/proxy0/listener] INFO: Listening on: [172.17.0.5]:3300
1594640759.277120 [/event/system] INFO: Starting event system.
1594640759.277190 [/io/thread] INFO: Starting IO thread.
1594640762.072489 [/wanproxy/proxy0/listener] DEBUG: void ProxyListener::accept_complete(Event, Socket*): Accepted client: [10.50.50.10]:57580
1594640762.072744 [/wanproxy/proxy0/connector] DEBUG: void ProxyConnector::on_request_data(Event): Flushing request
1594640762.072964 [/wanproxy/proxy0/connector] DEBUG: void ProxyConnector::on_response_data(Event): Flushing response


Client
------

create codec codec0
set codec0.codec XCodec
set codec0.cache COSS
set codec0.cache_path "/var/lib/wanproxy"
set codec0.local_size 2048
set codec0.compressor zlib
set codec0.compressor_level 6
set codec0.byte_counts 1
activate codec0

create interface if0
set if0.family IPv4
set if0.host "172.17.0.2"
set if0.port "3300"
set if0.proto TCP
activate if0

create peer peer0
set peer0.family IPv4
set peer0.host "10.50.50.7"
set peer0.port "3300"
set peer0.proto TCP
activate peer0

create proxy proxy0
set proxy0.interface if0
set proxy0.interface_codec codec0
set proxy0.peer peer0
set proxy0.peer_codec None
set proxy0.role Client
activate proxy0


1594640757.212075 [/wanproxy] INFO: WANProxy MT 3.0.5
1594640757.212108 [/wanproxy] INFO: Copyright (c) 2008-2013 WANProxy.org
1594640757.212119 [/wanproxy] INFO: Copyright (c) 2013-2018 Bramfeld-Software
1594640757.212129 [/wanproxy] INFO: All rights reserved.
1594640757.212155 [/wanproxy/config] INFO: Configuring WANProxy.
1594640757.213511 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Cache file: /var/lib/wanproxy/e2582903-602d-4066-a70f-89181ad6d16c.wpc
1594640757.213541 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Max size: 2148409344
1594640757.213550 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe size: 1056768
1594640757.213559 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe header size: 8192
1594640757.213569 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Serial: 1
1594640757.213579 [xcodec/cache/coss] DEBUG: XCodecCacheCOSS::XCodecCacheCOSS(const UUID&, const string&, size_t): Stripe number: 0
1594640757.213593 [/wanproxy/config/cache/type] INFO: 1
1594640757.213604 [/wanproxy/config/cache/path] INFO: /var/lib/wanproxy
1594640757.213614 [/wanproxy/config/cache/size] INFO: 2048
1594640757.213623 [/wanproxy/config/cache/uuid] INFO: e2582903-602d-4066-a70f-89181ad6d16c
1594640757.213897 [/wanproxy/proxy0/listener] INFO: Listening on: [172.17.0.2]:3300
1594640757.213926 [/event/system] INFO: Starting event system.
1594640757.214019 [/io/thread] INFO: Starting IO thread.
1594640762.072737 [/wanproxy/proxy0/listener] DEBUG: void ProxyListener::accept_complete(Event, Socket*): Accepted client: [172.17.0.1]:53946
1594640762.073236 [/zlib/inflate] ERR: virtual bool InflateFilter::consume(Buffer&, int): inflate(): data error
1594640762.073252 [/wanproxy/proxy0/connector] DEBUG: void ProxyConnector::on_request_data(Event): Flushing request
1594640762.074017 [/wanproxy/proxy0/connector] DEBUG: void ProxyConnector::on_response_data(Event): Flushing response

**Comment by bramfeld** [comment]
A client cannot have an interface_codec because nobody is sending encoded data to him. 
Only the server has a codec in its interface, which receives the data encoded by the client. 
At the client side, the peer must have a peer_codec matching the codec of the server interface, and its address must be the one where the server is listening.

**Comment by aharalambopoulos** [comment]
Could you please share the correct client config?

**Comment by bramfeld** [comment]
This could be a config for your client:

create codec codec0
set codec0.codec XCodec
set codec0.cache COSS
set codec0.cache_path "/var/lib/wanproxy"
set codec0.local_size 2048
set codec0.compressor zlib
set codec0.compressor_level 6
activate codec0

create interface if0
set if0.family IPv4
set if0.host "172.17.0.2"
set if0.port "3300"
set if0.proto TCP
activate if0

create peer peer0
set peer0.family IPv4
set peer0.host "172.17.0.5"
set peer0.port "3300"
set peer0.proto TCP
activate peer0

create proxy proxy0
set proxy0.interface if0
set proxy0.interface_codec None
set proxy0.peer peer0
set proxy0.peer_codec codec0
set proxy0.role Client
activate proxy0

The option byte_counts will print some totals of transmitted bytes for informative purposes, but it will add an extra filter to the proxy, so for maximal performance you should leave this option off.

**Comment by aharalambopoulos** [comment]
Thanks. It works fine and the gain the high using not encrypted traffic.
I tried using https ( docker pull  ...)   but the gain is zero ( as expected).

Any possibility to develop an 
set if0.proto https

**Comment by bramfeld** [comment]
No plans about that for the moment. Encryption masks the repetition of patterns, on which is based the WanProxy algorithm, so a full new approach would be needed here (and a strong sponsor to implement it).
